### ISSUE TITLE
Custom tooltip z-index issue

### ISSUE THREAD

**Issue by YSFKBDY** [mattlewis92/angular-calendar#1383]
When I add custom tooltips to events, it works perfectly. But, because of painting order, when I hover the mouse to an event on Monday and it's tooltip becomes visible, it stays back of tuesday's event(s), or same day's below event(s). However, when I hover the mouse to an event on Tuesday and it's tooltip becomes visible, it stays on top of monday's event(s) and stays on top of same day's previous event(s), and yet again it stays back of same day's event(s) and Wednesday's event(s). Here is some screenshots:

**Screenshots**
![dasdad](https://user-images.githubusercontent.com/27686947/101765027-cfa29480-3af1-11eb-830d-23b74e3eec55.jpg)
![sdfsdfsf](https://user-images.githubusercontent.com/27686947/101765031-d03b2b00-3af1-11eb-80c5-34d478b326f5.jpg)

**Versions**

- `@angular/core`: 10.2.0
- `angular-calendar`: 5.4.0
- Browser name and version: Win10 64 Bit Chrome

**Comment by JaxonWright** [comment]
You should be able to adjust the z-index of the tooltip via css in order to make it always on top of the events.

**Comment by YSFKBDY** [comment]
Yeah, I fixed it, thanks.

**Comment by calldeludo** [comment]
hello guys, i've been trying to fix my z-index problem but i couldnt find the solution... i'm using ngx-bootstrap/tooltip for the custom template... but my weekView still hiding some parts of the "dialog"... could you please share the solution?
@YSFKBDY @JaxonWright 

Thanks in advance...

**Comment by JaxonWright** [comment]
@calldeludo just add CSS that will apply to the tooltip with something like `z-index: 9999`

**Comment by calldeludo** [comment]
@JaxonWright well... it is my class 
`.customPopOverClass {
    min-width: 300px;
    max-width: 370px;
    color: rgb(0, 0, 0) !important;
    background-color: #fff !important;
    border-style: solid;
    border-color: grey;
    z-index: 9999;
}`
But still not working... do you know any StackBlitz or plunker with any working example? 
I am a bit desperated... the only tooltip that works for me is mat-tooltip but this library does not accept custom templates...

**Comment by JaxonWright** [comment]
@calldeludo can you make a stackblitz for others to look at?

**Comment by calldeludo** [comment]
@JaxonWright sure!
[https://stackblitz.com/edit/angular-9p7fgu?file=main.ts](url)

Just add some events and mouse over an event and check it... 
The custom template to this popover is in line.

here is what i mean
![image](https://user-images.githubusercontent.com/38619139/179142338-9966c0cc-d90b-46ff-a3d6-31141b699d3e.png)

Thanks a lot for your help... i really apreciate it. Is very important for me to display a custom template without buggs

**Comment by JaxonWright** [comment]
@calldeludo it seems to just be the order things are rendered. The later events are rendered after the earlier ones and the tooltip is grouped with the earlier event. I am not sure of a way around that at this moment, unfortunately.

**Comment by calldeludo** [comment]
@JaxonWright yea... the funny part is that those events are already rendered in DOM, even with a setTimeout mouseover i still have the same problem...  with angular material using a mat-tooltip is working perfectly... but i couldn't find the way to implement a new directive to pass a custom template... 
@mattlewis92 implemented a custom template for tooltips, but this approach has the same problem. events after are over the tooltip...
so... nobody know a working example? @YSFKBDY  said he fixed it...
Thanks for your time

**Comment by YSFKBDY** [comment]
> @JaxonWright yea... the funny part is that those events are already rendered in DOM, even with a setTimeout mouseover i still have the same problem... with angular material using a mat-tooltip is working perfectly... but i couldn't find the way to implement a new directive to pass a custom template... @mattlewis92 implemented a custom template for tooltips, but this approach has the same problem. events after are over the tooltip... so... nobody know a working example? @YSFKBDY said he fixed it... Thanks for your time

Hi, I've been on vacation and will be at the office on Monday. Will check my code and send you how to solve it.

**Comment by calldeludo** [comment]
@JaxonWright @YSFKBDY  i fixed the problem. I still dont understand why z-index does not fix it but.... i could find a solution changing the "container focus", adding this parametre...
`container="body"`
all is working good now....
Thank you guys for you attention and time :) 
Good coding!
