### ISSUE TITLE
Events Not Displaying Unless I Click on Calendar

### ISSUE THREAD

**Issue by brettgibson5** [mattlewis92/angular-calendar#204]
Was using the [refresh] observable to refresh my month view when I got the events back from my API source. This used to be working & now just shows a blank calendar, but if I click on any part of the calendar, the events populate perfectly. Any idea what the issue is here?

Much appreciated,
Brett

### Versions

Angular: 4.1.2

Calendar library: 0.14.0

Browser name and version: Chrome

**Comment by mattlewis92** [comment]
Can you make a plunker that reproduces your issue? Thanks!

**Comment by brettgibson5** [comment]
I actually figured it out (not plunkr but hope this can shed some light just on here). In our calendar, we get the results from the API and then run it through a loop (called `loopThroughEvents()`). Then, I would use the `this.refresh.next()` and should refresh the view. The solution oddly came by just commenting out the changeDetectionStrategy.OnPush line. This very well may be a unique bug because of our data, but if not, hope this is enough information to share.
```
@Component({
  selector: 'vendor-calendar-dashboard',
  // changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './calendar-dashboard.component.html',
  styleUrls: ['./calendar-dashboard.component.scss'],
})
```
```
events: CalendarEvent[];
refresh: Subject<any> = new Subject();
```
```
ngOnInit() {
  this.getCalendarEvents();
}

loopThroughEvents(res){
  var obj: Array<any> = [];
  for (var i = 0; i < res.length; i++) {
    var event: Object = {
      id: res[i]['id'],
      title: res[i]['title'],
      color: this.color,
      repeating: res[i]['repeating'],
      start: new Date(res[i]['start']),
      end: new Date(res[i]['end'])
    }
    obj.push(event)
  }
  this.events = obj;
  this.refresh.next();
}

getCalendarEvents() {
  return this.trucksService.getCalendarEvents()
    .subscribe( data => {
      this.loopThroughEvents(data);
    })
}
```

**Comment by mattlewis92** [comment]
Ah thanks for explaining that a bit more, I believe the issue was caused by using `detectChanges` instead of `markForCheck`, for anyone interested [this is a really good explanation](http://stackoverflow.com/questions/41364386/whats-the-difference-between-markforcheck-and-detectchanges) of the difference between the two. Should be fixed now in 0.15.1, thanks for reporting! 😃

**Comment by sixsixtrample** [comment]
( I know this is closed, but it seemed the best continuation of the issue)

I am getting this same error. If I use `changeDetection: ChangeDetectionStrategy.OnPush,` I have to click on the header to make the calendar appear, but if I comment this out I get an error in the console when clicking on the 'week' view.

`CalendarWeekViewComponent.html:11 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '181'. Current value: '183'.`

It still switches the view, but I see that error in the console. I am using a service to update an observable with events like so:

`
  fetchEvents() {
    this.workItemTaskService.getWorkItemTasks().subscribe(data => {
      this.events$ = data.results.map(event => {
        return {
          start: new Date(event.scheduled_date),
          title: 'Test',
          color: colors.red,
          meta: {
            hours_required: event.hours_required
          }
        }
      });
    });

  }`

**Comment by johnDivek** [comment]
<mwl-calendar-month-view  [refresh]="refresh">   </mwl-calendar-month-view> in html
 refresh: Subject<any> = new Subject(); in ts
once response from http call use just use this
 this.refresh.next();
oooooooooooooooooo that works

**Comment by paolagodoy** [comment]
> 
> 
> <mwl-calendar-month-view [refresh]="refresh"> in html
> refresh: Subject = new Subject(); in ts
> once response from http call use just use this
> this.refresh.next();
> oooooooooooooooooo that works

Gracias! esto me funcionó perfecto

**Comment by giridhar196** [comment]
I am still facing the same issue. The data is not loading when I click on previous button.

Steps Followed : 
1. Load the data from API
2. Try to add the data to events array.
3. Added the following after the for each loop
this.refresh  = new Subject();
this.refresh.next();
4. Data is not appearing on the calendar. 

FYI  : When I click on Next button the data is loading properly, but When I click on previous it is not loading in the calendar.
Is there any other way I can refresh the calendar.
