### ISSUE TITLE
ng server --aot --> TypeError: this.moment is not a function

### ISSUE THREAD

**Issue by Upimage** [mattlewis92/angular-calendar#403]
## I'm submitting a ...

<pre>
[ x] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
When running my app with `ng serve --aot` I'm getting an error after navigation to the page of the component:
`ERROR TypeError: this.moment is not a function
    at CalendarMomentDateFormatter.webpackJsonp.../../../../angular-calendar/modules/common/calendar-moment-date-formatter.provider.js.CalendarMomentDateFormatter.monthViewDayNumber (calendar-moment-date-formatter.provider.js:40)
    at CalendarDatePipe.webpackJsonp.../../../../angular-calendar/modules/common/calendar-date.pipe.js.CalendarDatePipe.transform (calendar-date.pipe.js:17)
    at checkAndUpdatePureExpressionInline (core.es5.js:11642)
    at checkAndUpdateNodeInline (core.es5.js:12345)
    at checkAndUpdateNode (core.es5.js:12284)
    at debugCheckAndUpdateNode (core.es5.js:13141)
    at debugCheckRenderNodeFn (core.es5.js:13120)
    at Object.updateRenderer (calendar-month-cell.component.ngfactory.ts:125)
    at Object.debugUpdateRenderer [as updateRenderer] (core.es5.js:13105)
    at checkAndUpdateView (core.es5.js:12256)`

Runnung without --aot flag does not raise an exception.

Is something wrong with my configurations?
Please, any hints are welcome!

### Minimal reproduction of the problem with instructions
My component looks like this:
`import * as moment from 'moment';
import {
  CalendarEvent, CalendarEventTimesChangedEvent, MOMENT,
  CalendarDateFormatter, CalendarMomentDateFormatter, CalendarEventTitleFormatter
} from "angular-calendar";

@Component({
  selector: 'app-create-schedule-panel',
  templateUrl: './create-schedule-panel.component.html',
  styleUrls: ['./create-schedule-panel.component.css'],
  providers: [
    { provide: CalendarDateFormatter, useClass: CalendarMomentDateFormatter },
    { provide: MOMENT, useValue: moment },
    { provide: CalendarEventTitleFormatter, useClass: CustomEventTitleFormatter }
  ]
})
export class CreateSchedulePanelComponent implements OnInit{..}`
### Versions

Angular:  4.4.6

Calendar library: 0.22.1
Moment: 2.19.2

Browser name and version: Chrome 62.0.3202.94

**Comment by mattlewis92** [comment]
I believe this is caused by the CLI forcing module=es2015 on AoT, thus you will need to adjust your import a bit to make it work:
```
import moment from 'moment';
```

and set `allowSyntheticDefaultImports` to true in your tsconfig.

**Comment by Upimage** [comment]
Thank you for your help, but I still got the same exception. 

I have implemented my own formatter which was little work to do. 
Here is my class:
`import { CalendarDateFormatterInterface, DateFormatterParams } from "angular-calendar";
import * as moment from 'moment';

export class MyCalMomentDateFormatter implements CalendarDateFormatterInterface {

  constructor() { }

  monthViewColumnHeader({ date, locale }: DateFormatterParams): string {
    return moment(date)
      .locale(locale)
      .format('dddd');
  }

  monthViewDayNumber({ date, locale }: DateFormatterParams): string {
    return moment(date)
      .locale(locale)
      .format('D');
  }

  monthViewTitle({ date, locale }: DateFormatterParams): string {
    return moment(date)
      .locale(locale)
      .format('MMMM YYYY');
  }

  weekViewColumnHeader({ date, locale }: DateFormatterParams): string {
    return moment(date)
      .locale(locale)
      .format('ddd');
  }

  weekViewColumnSubHeader({ date, locale }: DateFormatterParams): string {
    return moment(date)
      .locale(locale)
      .format('D MMM');
  }

  weekViewTitle({ date, locale }: DateFormatterParams): string {
    return moment(date)
      .locale(locale)
      .format('[Woche] W [/] YYYY');
  }

  dayViewHour({ date, locale }: DateFormatterParams): string {
    return moment(date)
      .locale(locale)
      .format('HH:mm');
  }
 
  dayViewTitle({ date, locale }: DateFormatterParams): string {
    return moment(date)
      .locale(locale)
      .format('dd, DD.MM.YYYY');
  }
}`

**Comment by Kumfert** [comment]
Proposed solution from @mattlewis92 didn't work for me, either. 
Workaround from @Upimage did work.

Perhaps this independent result merits having the issue reopened?

**Comment by mattlewis92** [comment]
Ah, I think this is an issue with how the angular 4 AoT compiler works. If you upgrade to angular v5 or use this way of providing moment then it should work:

```
export function momentFactory() {
  return moment;
}

{ provide: MOMENT, useFactory: momentFactory },
```

I only had time to test it with an angular v5 app and that seemed to work ok.

**Comment by RafiHenig** [comment]
We're having the same issue,after trying @mattlewis92 solution we still have the problam.
