### ISSUE TITLE
Clicking a day with no events leads to the wrong day when selecting day view

### ISSUE THREAD

**Issue by maxtime-wfm** [mattlewis92/angular-calendar#669]
**Describe the bug**
When selecting a day (in week/month view) that has events, and then changing to day view, the correct day shows. However, selecting a day with no events causes the day view to show the last clicked day that had events.

**Minimal reproduction of the problem with instructions**
You can recreate this issue by going onto the kitchen sink demo, clicking a day which has events and changing to day view, then going back to month view, clicking a day with no events, and changing back to day view.

**Versions**
- `@angular/core`: 6.0.5
- `angular-calendar`: 0.25.2
- Browser name and version: Chrome 67.0.3396.99

**Comment by mattlewis92** [comment]
Thanks for reporting, I've fixed this in the demo now (the bug is with the demo code so you'll need to apply the fix to your own code)

**Comment by maxtime-wfm** [comment]
Could you tell me which part of the demo code to look at to see the fix please?

**Comment by mattlewis92** [comment]
Sure, it's all on the commit diff: https://github.com/mattlewis92/angular-calendar/commit/6093890f1b1652346f77eb9d8332c0001783e759

**Comment by maxtime-wfm** [comment]
The fix for month to day works perfectly but there is still an issue when going from week to day. If I try clicking on the day heading, or where the events would be if there were any, it doesn't update that day to be the selected day.

**Comment by mattlewis92** [comment]
You need to implement that logic yourself, when you click anything in the calendar all it does it emit an output event that you need to handle. If you do `(dayHeaderClicked)="viewDate = $event.date"` on the week view it should handle it the way you want.

**Comment by maxtime-wfm** [comment]
For anyone looking in the future:

I had to add `(dayHeaderClicked)="dayClicked($event.day)"` to the html for my week view.

I then also changed the `dayClicked()` function in the typescript so that `if ( (isSameDay(this.viewDate, date) && this.activeDayIsOpen === true)  || events.length === 0 )` is now `if ( (isSameDay(this.viewDate, date) && this.activeDayIsOpen === true) )`.
