### ISSUE TITLE
Duplicate identifier in date-fns?

### ISSUE THREAD

**Issue by G3nius** [mattlewis92/angular-calendar#849]
**Describe the bug**

I tried to build the project and got multiple errors. I'm using Windows so I might be the problem.

When I run ng build I get these errors:

`ERROR in node_modules/date-fns/add_months/index.d.ts(3,12): error TS2300: Duplicate identifier 'addMonths'. node_modules/date-fns/add_weeks/index.d.ts(3,12): error TS2300: Duplicate identifier 'addWeeks'. node_modules/date-fns/get_date/index.d.ts(3,12): error TS2300: Duplicate identifier 'getDate'. node_modules/date-fns/get_iso_week/index.d.ts(3,12): error TS2300: Duplicate identifier 'getISOWeek'. node_modules/date-fns/get_year/index.d.ts(3,12): error TS2300: Duplicate identifier 'getYear'. node_modules/date-fns/set_date/index.d.ts(3,12): error TS2300: Duplicate identifier 'setDate'. node_modules/date-fns/set_month/index.d.ts(3,12): error TS2300: Duplicate identifier 'setMonth'. node_modules/date-fns/set_year/index.d.ts(3,12): error TS2300: Duplicate identifier 'setYear'. node_modules/date-fns/sub_days/index.d.ts(3,12): error TS2300: Duplicate identifier 'subDays'. node_modules/date-fns/sub_months/index.d.ts(3,12): error TS2300: Duplicate identifier 'subMonths'. node_modules/date-fns/sub_weeks/index.d.ts(3,12): error TS2300: Duplicate identifier 'subWeeks'. node_modules/date-fns/typings.d.ts(911,12): error TS2300: Duplicate identifier 'addMonths'. node_modules/date-fns/typings.d.ts(926,12): error TS2300: Duplicate identifier 'addWeeks'. node_modules/date-fns/typings.d.ts(1136,12): error TS2300: Duplicate identifier 'getDate'. node_modules/date-fns/typings.d.ts(1171,12): error TS2300: Duplicate identifier 'getISOWeek'. node_modules/date-fns/typings.d.ts(1221,12): error TS2300: Duplicate identifier 'getYear'. node_modules/date-fns/typings.d.ts(1476,12): error TS2300: Duplicate identifier 'setDate'. node_modules/date-fns/typings.d.ts(1521,12): error TS2300: Duplicate identifier 'setMonth'. node_modules/date-fns/typings.d.ts(1536,12): error TS2300: Duplicate identifier 'setYear'. node_modules/date-fns/typings.d.ts(1606,12): error TS2300: Duplicate identifier 'subDays'. node_modules/date-fns/typings.d.ts(1631,12): error TS2300: Duplicate identifier 'subMonths'. node_modules/date-fns/typings.d.ts(1646,12): error TS2300: Duplicate identifier 'subWeeks'.`

Seems like date-adapters is suppoose to import these identifiers from date-fns so I guess typings.d.ts shouldn't be included in the build? Maybe it's a file-system problem because I'm using Windows?

**Minimal reproduction of the problem with instructions**

Just checked out the project and ran npm install, then ng build, on my Windows PC.

**Screenshots**

![image](https://user-images.githubusercontent.com/2564305/51029620-8b25bb80-159f-11e9-93b8-0d396e17cc8a.png)

**Versions**

- `@angular/core`: 6.1.10
- `angular-calendar`: latest
- Browser name and version: N/A

**Comment by G3nius** [comment]
I fixed this by editing date-adapters\date-fns\index.ts and changin these imports:
import * as addWeeks from 'date-fns/add_weeks/index';
to:
import * as addWeeks from 'date-fns/add_weeks';

If I understand correctly, date-fns declares the exports itself in typings.d.ts, so when you import directly from the inner directories you get duplicate definitions.
But I can't figure out why import with /index in the first place, or how it work for anyone else the way it is.

**Comment by mattlewis92** [comment]
I can reproduce, it looks like something broke in a newer date-fns release, if you do

```
npm i date-fns@1.29.0
```

To use the last working version it should work for now, I'll send them a PR with a fix

**Comment by mattlewis92** [comment]
Sent a fix to date-fns: https://github.com/date-fns/date-fns/pull/1082 Once that's merged and released everything should start working 😄 Closing this issue as there's nothing actionable from this end.

**Comment by jakewies** [comment]
This issue still exists, I'd re-open.

I'm having the problem with `date-fns@next` and [`material-ui-pickers](https://github.com/dmtrKovalenko/material-ui-pickers).

**Comment by iamchathu** [comment]
Issue is there for 2.6.0 version.

```bash
2:22  error  '/Users/Me/Workspace/project/packages/shared/node_modules/date-fns/typings.d.ts' imported multiple times  import/no-duplicates
  3:20  error  '/Users/Me/Workspace/project/packages/shared/node_modules/date-fns/typings.d.ts' imported multiple times  import/no-duplicates
```
